<!--
<form action="?" method="POST">
    <label for="usernameing Lao">Username:</label>
        <input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
    <label for="password">Password:</label>
        <input type="password" name="password" id="password" maxlength="20" size="20" /><br/>
    <input type="submit" />
</form>-->
  <h1> Welcome to Cooking Lao!</h1>
    
    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Soups</a></li>
            <li><a href="#">Stews</a></li>
            <li><a href="#">Salads</a></li>
            <li><a href="#">Sauces</a></li>
            <li><a href="#">Snacks</a></li>
            <li><a href="#">Desserts</a></li>
        </ul>
    </nav>
    
    <aside>
        <h2>Login here!</h2>
        <form action="?" method="POST">
            <label for="usernameing Lao">Username:</label>
                <input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
            <label for="password">Password:</label>
                <input type="password" name="password" id="password" maxlength="20" size="20" /><br/>
            <input type="submit" />
        </form>
    </aside>